### ISSUE TITLE
My balance disappeared

### ISSUE THREAD

**Issue by TutaRex** [BTCP-community/electrum-zcl#192]
I bought ZCL on Bittrex and sent it to my Zclassic Electrum 1.0.6
( t1eHpiTcxGqZURbRKxims4kcnqL9Wa9dFNU )

I saw the deposit in first but today I wanted to check it and balance is 0. ZCL
I send You screenshoots to see..

![zclassic txid check](https://user-images.githubusercontent.com/46775623/51302809-c149bc00-1a33-11e9-9363-c6b58490e3bd.jpg)
![zcl wallet balance](https://user-images.githubusercontent.com/46775623/51302810-c149bc00-1a33-11e9-88b6-1251cdadb5aa.jpg)

Can You please help me and see what is going on with my money?

**Comment by Freeter-Prince** [comment]
I had the same issue, how's yours got solved? And when I tried to check the transaction info in the wallet, the Electrum 1.0.6 just crashed.

**Comment by TutaRex** [comment]
My balance showed in a two days.. I don't know what happened but it is
solved now.. Maybe this:

A guy told me to add server to my servers list, double click to red button
on the buttom right, and then SERVERS tab. I have 3 servers there:


electrum.schlachter.mx                50002
electrum.zclassic.community       50002
zclele.duckdns.org                       50002
