### ISSUE TITLE
Version 1.0.6 Balance/Deposit Error

### ISSUE THREAD

**Issue by Freeter-Prince** [BTCP-community/electrum-zcl#199]
As shown, the latest deposit in the wallet shows a verified transaction, but the amount is zero, and it shows a successful transaction both on Bittrex.com and the blockchain explorer. Also, the wallet address changes by itself.
My wallet address: t1QUqZzDtAYghZrDhgTLQpTeC35vCJ9P8eL
![image](https://user-images.githubusercontent.com/46234083/53690180-8e1f7a00-3da0-11e9-97ab-450a7be36167.png)
![image](https://user-images.githubusercontent.com/46234083/53690184-94adf180-3da0-11e9-8f22-5653ac662087.png)

**Comment by mexican1973** [comment]
There was a network upgrade to migrate to sapling to support more efficient processing of shielded transactions. You will have to upgrade your electrum client.
The z-classic github is also outdated and should not be used anymore.
The official Software can be found here:

https://github.com/ZclassicCommunity/electrum-zcl
