### ISSUE TITLE
Did you check komodo wallet?

### ISSUE THREAD

**Issue by sgaragagghu** [BTCP-community/electrum-zcl#5]
Maybe it's easiest to adapt.
Don't sure if there are a electrum-komodo
You may ask help to komodo guys: http://slackinvite.supernet.org/

**Comment by Mrwh0** [comment]
please point me to the repo.

**Comment by sgaragagghu** [comment]
https://github.com/SuperNETorg/Agama
it seems to work on top of supernet instead of a electrum server, but already support zcash.
As i understood, it may work without download the blockchain only with transparent tx.

**Comment by csulmone** [comment]
Why is it looking to start a zcashd node?
https://github.com/ca333/komodoGUI/blob/master/src/java/com/vaklinov/zcashui/Komodo.java#L401

**Comment by Mrwh0** [comment]
Thank you,  that will not work for us.
